### ISSUE TITLE
Recursive Lazy instances not lazy enough

### ISSUE THREAD

**Issue by DarkDimius** [kaitai-io/kaitai_struct_compiler#70]
The following example illustrates use of a format where you need to find size of a recursive datastructure that isn't explicitly written but is implicitly encoded.
More specifically, this is indended to count number of continuous bits before a stobit is hit.

```
meta:
  id: tmp
  file-extension: tmp
  endian: be
seq:
  - id: r
    type: Rec
types:
  Rec:
   seq:
    - id: bit
      type: u1
    - id: nxt
      if: bit < 128 
      type: Rec
   instances:
     count_reverse:
       type: u1
       value: "bit < 128? nxt.count_reverse + 1 : 0"
```

```
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at io.kaitai.struct.TypeProcessor$.getInstanceDataType(TypeProcessor.scala:276)
	at io.kaitai.struct.TypeProcessor$$anonfun$markupParentTypes$2.apply(TypeProcessor.scala:225)
	at io.kaitai.struct.TypeProcessor$$anonfun$markupParentTypes$2.apply(TypeProcessor.scala:224)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at io.kaitai.struct.TypeProcessor$.markupParentTypes(TypeProcessor.scala:224)
	at io.kaitai.struct.TypeProcessor$.markupParentAs(TypeProcessor.scala:260)
	at io.kaitai.struct.TypeProcessor$.markupParentAs(TypeProcessor.scala:249)
	at io.kaitai.struct.TypeProcessor$.markupParentTypesAdd(TypeProcessor.scala:232)
	at io.kaitai.struct.TypeProcessor$$anonfun$markupParentTypes$1.apply(TypeProcessor.scala:222)
	at io.kaitai.struct.TypeProcessor$$anonfun$markupParentTypes$1.apply(TypeProcessor.scala:221)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.kaitai.struct.TypeProcessor$.markupParentTypes(TypeProcessor.scala:221)
	at io.kaitai.struct.TypeProcessor$.processTypes(TypeProcessor.scala:17)
	at io.kaitai.struct.formats.JavaKSYParser$.localFileToSpec(JavaKSYParser.scala:17)
	at io.kaitai.struct.Main$.compileOne(Main.scala:83)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:120)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:115)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.kaitai.struct.Main$.main(Main.scala:115)
	at io.kaitai.struct.Main.main(Main.scala)
```

**Comment by GreyCat** [comment]
Here's what happens when you try to compile that with `--verbose` turned on in current compiler:

```
### deriveValueType: iteration #1
deriveValueType(tmp)
deriveValueType(tmp::rec)
count_reverse type undecided: count_reverse
```

That is:

* type derivation engine tries to derive type for `tmp::rec::count_reverse'
* for that, it needs to derive types for `nxt.count_reverse + 1` and `0` and combine them
* for that, it needs to derive type `nxt` and find `count_reverse` member of it
* it finds that `nxt` is of type `rec` (that's easy), finds its member `count_reverse`, and, alas, we've got an infinite loop

Alas, the only way out of this, I believe, is to declare that type somehow manually, which is currently not supported for value instances.

Actually, there's more to that problem, as we don't really have a clear way to specify these *types* in .ksy, at least yet. Stuff like `type: u4` or `type: str` is more than that: it carries not only the type information, but also some information on data representation in the byte stream, which is actually not needed here. And, for example, there's no `type: ...` for byte arrays — omitting `type` makes attribute to be parsed as byte array, etc.

**Comment by DarkDimius** [comment]
Did I get it right that `       type: u1` was ignored?

 
FYI: in general inferring a type of a recursive expression isn't possible.
E.g. Scala doesn't do it.

**Comment by GreyCat** [comment]
Yeah, right now it's ignored. Actually, it's (yet another) parsing bug: lack of check for unused YAML keys in this case. I'll try to fix it now — at least a clear error message should appear in this case.

As for general inferring — basically, yes, we need a way to enforce a data type in these cases. Internally, ksc has concepts of `CalcIntType`, `CalcStrType`, etc, for these purposes — but we need some mechanism to expose that in .ksy. From designer's point of view, it should *not* be `type: ...`, to reduce confusion.

May be something like `enforce-type: int`, `enforce-type: str`, `enforce-type: float`, `enforce-type: usertype(foo)`?

**Comment by GreyCat** [comment]
> So, it can reorder that, and determine the type of `0` first

No, it can't. First of all, such transformations are relatively untrivial and heavily dabble into field of symbolic evaluation / calculus. And, even if we did that for numbers, `+` is not commutitative for strings.

Loop detection is pretty untrivial as well. There could be several valid solutions, for example. There could be none. Sometimes you'll have to visit the attribute more than once in such a decent.

Anyway, there is consensus that recursive expressions are not the good way to solve fold/inject-style problems in KS. Most likely we'll end up with proper functions or at least some ready-made substitutes like `min`, `max`, `sum`, etc.
