### ISSUE TITLE
Exception in thread "main" unacceptable character (0x1) special characters are not allowed

### ISSUE THREAD

**Issue by neiromc** [kaitai-io/kaitai_struct_compiler#8]
Hi!

Latest version of kaitai-struct-compiler 0.4 does not work for me. 
I try to use gif & png ksy files from yours git repo with files in same format, but I have Exception message in all cases.

### **GIF**

Exception in thread "main" unacceptable character '' (0x1) special characters are not allowed
in "<reader>", position 7
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:97)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:190)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:148)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:521)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createJsonParser(YAMLFactory.java:405)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1965)
	at io.kaitai.struct.ClassCompiler$.localFileToSpec(ClassCompiler.scala:225)
	at io.kaitai.struct.ClassCompiler$.fromLocalFileToFile(ClassCompiler.scala:229)
	at io.kaitai.struct.Main$.compileOne(Main.scala:80)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:115)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:111)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.kaitai.struct.Main$.main(Main.scala:111)
	at io.kaitai.struct.Main.main(Main.scala)

### **PNG**

Exception in thread "main" unacceptable character '�' (0xFFFD) special characters are not allowed
in "<reader>", position 0
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:97)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:190)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:62)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:148)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:521)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createJsonParser(YAMLFactory.java:405)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1965)
	at io.kaitai.struct.ClassCompiler$.localFileToSpec(ClassCompiler.scala:225)
	at io.kaitai.struct.ClassCompiler$.fromLocalFileToFile(ClassCompiler.scala:229)
	at io.kaitai.struct.Main$.compileOne(Main.scala:80)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:115)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:111)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.kaitai.struct.Main$.main(Main.scala:111)
	at io.kaitai.struct.Main.main(Main.scala)

More thanks!

**Comment by GreyCat** [comment]
Looks like that in both cases something happened to the .ksy files - for GIF, you've got a control character 0x1 at position 7, and for PNG if seems like you've got Unicode replacement character (0xFFFD) in the very beginning. Could you check file sizes and checksums (for example, md5 or sha1)? If should be like that:

* gif.ksy - 1563 bytes
* png.ksy - 2191 bytes

MD5:

    3c47cc8a191deb422c56769fdd059285  gif.ksy
    2963b6f07698be8861e0bf89338a9e51  png.ksy

SHA1:

    c05b092a021b4675aa71fb56bbc4c9d21102817c  gif.ksy
    e83bc49c7a9ba13b48954796fe72702d9999aeff  png.ksy

**Comment by neiromc** [comment]
Thanks for reply!

md5:
```
MD5 (gif.ksy) = 3c47cc8a191deb422c56769fdd059285
MD5 (png.ksy) = 2963b6f07698be8861e0bf89338a9e51
```
Sizes:
```
1563 gif.ksy
2191 png.ksy
```

I download this files as zip.

**Comment by GreyCat** [comment]
Thank you for taking your time to try KS and reporting the problem.

Could you tell me more details:

1. What is your OS, working environment, Java environment versions, system language / encoding, etc?
2. What distribution of KS v0.4 are you using - i.e. .zip, .msi, .deb?
3. How are you invoking the compiler, i.e. the whole command line?
4. Does it work if you just copy the files you've got and paste them to http://kaitai.io/repl/ or it reports the same error with unacceptable character there?

**Comment by neiromc** [comment]
Yes, sure!

1) OSX El Capitan (10.11.5)
```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

locale is "en_US.UTF-8"
```

2) Download compiler as zip file
3) 
```
sh ./bin/kaitai-struct-compiler -t java --verbose me.png png.ksy
sh ./bin/kaitai-struct-compiler -t java --verbose cook.gif gif.ksy
```
4) I did try to copy and paste in left field gif and png ksy files, I press "Compile" and got no results in right field

**Comment by neiromc** [comment]
Ups: point 4 - it's safari problem. In firefox is work!

**Comment by GreyCat** [comment]
> `sh ./bin/kaitai-struct-compiler -t java --verbose me.png png.ksy`

Ah! It's just you're feeding the pictures into the compiler :) If you're using the compiler then you do something like that:

```
sh ./bin/kaitai-struct-compiler -t java --verbose png.ksy
```

Now you've got your `Png.java`, you can add it to your Java project and use it like that:

```java
Png myPng = Png.fromFile("me.png");
```

to parse your `me.png` file.

If you were looking for [visualizer](https://github.com/kaitai-io/kaitai_struct_visualizer) (if you don't want API yet, you just want to browse the structure), then you need to install it using `gem install kaitai-struct-visualizer` and then run it like that:

```
ksv me.png png.ksy
```

**Comment by neiromc** [comment]
Thanks!
I understand my mistake. Now it's work!

I try to use KSV, but have a problem:
```
./bin/ksv me.png png.ksy
sh: ksc: command not found
```

**Comment by GreyCat** [comment]
`ksv` requires you to have `kaitai-struct-compiler` available as `ksc` in your path. Probably the easiest way to get it to work would be adding a symlink like that (in root mode or using `sudo`):

```
ln -s /path/to/your/kaitai-struct/bin/kaitai-struct-compiler /usr/local/bin/ksc
```

Afterwards, you should be able to run `ksc` as a regular command, i.e.:

```
$ ksc --version
kaitai-struct-compiler 0.4
```

and thus `ksv` will work too.

**Comment by neiromc** [comment]
Symlink on ksc work perfect.
Which version Python needs?


```
$ ./bin/ksv me.png png.ksy

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- kaitai/struct/struct (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/folders/hy/scs7c3rx0fz9s4z1sfmc0n0r0000gn/T/d20160810-5624-lfz72m/png.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/neiro/Downloads/kaitai_struct_visualizer-master/lib/kaitai/struct/visualizer/visualizer_main.rb:15:in `block in compile_format'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
	from /Users/neiro/Downloads/kaitai_struct_visualizer-master/lib/kaitai/struct/visualizer/visualizer_main.rb:9:in `compile_format'
	from /Users/neiro/Downloads/kaitai_struct_visualizer-master/lib/kaitai/struct/visualizer/visualizer.rb:18:in `initialize'
	from ./bin/ksv:19:in `new'
	from ./bin/ksv:19:in `<main>'
```

**Comment by GreyCat** [comment]
Hmm, that's really strange. That's Ruby, not Python.

The message is about Kaitai Struct's Ruby runtime library, but it should have installed when you did `gem install kaitai-struct-visualizer`. Can you try to do `gem install kaitai-struct` manually?

**Comment by neiromc** [comment]
Yes, sure, Ruby))) sorry.

After using gem installer have:
```
$ ./kaitai_struct_visualizer-master/bin/ksv me.png ../kaitai_struct_formats-master/image/png.ksy
/var/folders/hy/scs7c3rx0fz9s4z1sfmc0n0r0000gn/T/d20160810-5722-k9sdgs/png.rb:78:in `inflate': buffer error (Zlib::BufError)
	from /var/folders/hy/scs7c3rx0fz9s4z1sfmc0n0r0000gn/T/d20160810-5722-k9sdgs/png.rb:78:in `_read'
	from /var/folders/hy/scs7c3rx0fz9s4z1sfmc0n0r0000gn/T/d20160810-5722-k9sdgs/png.rb:21:in `_read'
	from /Temp/kaitai_struct_visualizer-master/lib/kaitai/struct/visualizer/visualizer.rb:29:in `initialize'
	from ./bin/ksv:19:in `new'
	from ./bin/ksv:19:in `<main>'

```

**Comment by GreyCat** [comment]
Cool, it seems to be working now.

This error Is an error with png file format - it tries to apply zlib deflate, but fails. You can just find this piece in .ksy file:

```yaml
      - id: body
        size: len
        process: zlib
        if: type == "IDAT"
```

and remove or comment out `process: zlib` line. Alternatively, you can try `gif.ksy` - it doesn't have any zlib there ;)

**Comment by neiromc** [comment]
Awesome! It's alive!
Thanks a lot!

**Comment by GreyCat** [comment]
Thank you for your patience and have a nice day :)

**Comment by neiromc** [comment]
Thanks you for this software and have a nice day too!
